services:
  osu-air-drop:
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
          ignore:
            - node_modules
            - volumes
            - .git
            - coverage
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
      - "9229:9229"
      - "9464:9464"
    env_file: .env.docker
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=prisma
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  postgres_data:
